# Generated by Django 3.0.5 on 2021-09-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='test',
            name='density',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='test',
            name='strength',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
