# Generated by Django 3.0.5 on 2021-09-08 12:24

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20210906_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitoring.Test')),
                ('name', models.CharField(default='', max_length=250)),
                ('phone', models.CharField(default='', max_length=250)),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
            },
            bases=('monitoring.test',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Проба', 'verbose_name_plural': 'Пробы'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='operator',
        ),
        migrations.AddField(
            model_name='test',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
